site_name: PUMAS LuaJIT
site_description: A LuaJIT wrapper for PUMAS
site_author: Valentin Niess
copyright: LGPL-3.0

repo_url: https://github.com/niess/pumas-luajit.git
edit_uri: edit/master/docs/docs

nav:
  - Home: index.md
  - API &raquo; Coordinates:
    - CartesianPoint: api/coordinates/CartesianPoint.md
    - CartesianVector: api/coordinates/CartesianVector.md
    - GeodeticPoint: api/coordinates/GeodeticPoint.md
    - HorizontalVector: api/coordinates/HorizontalVector.md
    - LocalFrame: api/coordinates/LocalFrame.md
    - SphericalPoint: api/coordinates/SphericalPoint.md
    - SphericalVector: api/coordinates/SphericalVector.md
    - Transform: api/coordinates/Transform.md
  - API &raquo; Data:
    - constants: api/data/constants.md
    - ELEMENTS: api/data/ELEMENTS.md
    - MATERIALS: api/data/MATERIALS.md
    - pdg: api/data/pdg.md
    - TopographyData: api/data/TopographyData.md
    - TopographyDataSet: api/data/TopographyDataSet.md
  - API &raquo; Geometry:
    - EarthGeometry: api/geometry/EarthGeometry.md
    - InfiniteGeometry: api/geometry/InfiniteGeometry.md
    - PolytopeGeometry: api/geometry/PolytopeGeometry.md
  - API &raquo; Medium:
    - GradientMedium: api/medium/GradientMedium.md
    - MEDIUM_TRANSPARENT: api/medium/MEDIUM_TRANSPARENT.md
    - UniformMedium: api/medium/UniformMedium.md
  - API &raquo; Physics:
    - build: api/physics/build.md
    - Element: api/physics/Element.md
    - Material: api/physics/Material.md
    - Physics: api/physics/Physics.md
    - TabulatedMaterial: api/physics/TabulatedMaterial.md
  - API &raquo; Primary:
    - MuonFlux: api/primary/MuonFlux.md
  - API &raquo; Simulation:
    - Context: api/simulation/Context.md
    - Event: api/simulation/Event.md
    - Recorder: api/simulation/Recorder.md
    - State: api/simulation/State.md
  - API &raquo; Others:
    - version: api/others/version.md

theme:
  name: readthedocs
  navigation_depth: 2
  highlightjs: true
  hljs_languages:
    - lua

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html

extra_css: [extra.css]
