site_name: PUMAS LuaJIT
site_description: A LuaJIT wrapper for PUMAS
site_author: Valentin Niess
copyright: LGPL-3.0

repo_url: https://github.com/niess/pumas-luajit
edit_uri: edit/master/docs/docs

nav:
  - Home: index.md
  - API &raquo; Topics:
    - Coordinates: api/Coordinates.md
    - Geometry: api/Geometry.md
    - Medium: api/Medium.md
    - Physics: api/Physics.md
    - Simulation: api/Simulation.md
  - API &raquo; Coordinates:
    - CartesianPoint: api/coordinates/CartesianPoint.md
    - CartesianVector: api/coordinates/CartesianVector.md
    - GeodeticPoint: api/coordinates/GeodeticPoint.md
    - HorizontalVector: api/coordinates/HorizontalVector.md
    - LocalFrame: api/coordinates/LocalFrame.md
    - SphericalPoint: api/coordinates/SphericalPoint.md
    - SphericalVector: api/coordinates/SphericalVector.md
    - UnitaryTransformation: api/coordinates/UnitaryTransformation.md
  - API &raquo; Data:
    - constants: api/data/constants.md
    - elements: api/data/elements.md
    - materials: api/data/materials.md
    - TopographyData: api/data/TopographyData.md
    - TopographyDataset: api/data/TopographyDataset.md
  - API &raquo; Geometry:
    - EarthGeometry: api/geometry/EarthGeometry.md
    - InfiniteGeometry: api/geometry/InfiniteGeometry.md
    - PolyhedronGeometry: api/geometry/PolyhedronGeometry.md
    - TopographyLayer: api/geometry/TopographyLayer.md
  - API &raquo; Medium:
    - GradientMedium: api/medium/GradientMedium.md
    - transparent_medium: api/medium/transparent_medium.md
    - UniformMedium: api/medium/UniformMedium.md
  - API &raquo; Physics:
    - build: api/physics/build.md
    - CompositeMaterials: api/physics/CompositeMaterials.md
    - Element: api/physics/Element.md
    - Material: api/physics/Material.md
    - Physics: api/physics/Physics.md
    - TabulatedMaterial: api/physics/TabulatedMaterial.md
  - API &raquo; Primary:
    - MuonFlux: api/primary/MuonFlux.md
  - API &raquo; Simulation:
    - Context: api/simulation/Context.md
    - Event: api/simulation/Event.md
    - Limit: api/simulation/Limit.md
    - Mode: api/simulation/Mode.md
    - Recorder: api/simulation/Recorder.md
    - State: api/simulation/State.md
  - API &raquo; Others:
    - Readonly: api/others/Readonly.md
    - version: api/others/version.md
  - Coverage: coverage/

theme:
  name: readthedocs
  navigation_depth: 2
  highlightjs: true
  hljs_languages:
    - lua

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.arithmatex # pip install pymdown-extensions

extra_css: [extra.css]


extra_javascript:
  - mathjax-config.js
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML


plugins:
  - mkdocs-simple-hooks:
      hooks:
        on_pre_build: 'docs.hooks:pre_build'
