name: Linux

on:
  push:
    branches:
      - master
    paths:
    - '.github/workflows/linux.yml'
    - 'Makefile'
    - 'src/**'

jobs:
  x86_64:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: |
        ./dist/linux.sh

    - name: Rock
      run: |
        ./dist/rock.sh ${{ secrets.LUAROCKS_TOKEN }}

    - name: Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        automatic_release_tag: linux
        title: Linux
        files: bin/luajit-pumas
        repo_token: ${{ secrets.GITHUB_TOKEN }}
