name: OSX

on:
  push:
    branches:
      - master
    paths:
    - '.github/workflows/osx.yml'
    - 'Makefile'
    - 'src/**'

jobs:
  x86_64:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: |
        make install PREFIX=$(pwd) MACOSX_DEPLOYMENT_TARGET=10.7

    - name: Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        automatic_release_tag: osx
        title: OSX
        files: bin/pumas-luajit
        repo_token: ${{ secrets.GITHUB_TOKEN }}
